### ISSUE TITLE
error: implicit declaration of function 'esp_partition_reload_table'

### ISSUE THREAD

**Issue by 1371030** [pebri86/esplay-base-firmware#5]
make flash

/Users/admin/esp/esplay-base-firmware-1.0-esplay-micro/main/main.c:399:5: error: implicit declaration of function 'esp_partition_reload_table' [-Werror=implicit-function-declaration]
     esp_partition_reload_table();

cc1: some warnings being treated as errors
make[1]: *** [main.o] Error 1
make: *** [component-main-build] Error 2

**Comment by pebri86** [comment]
I see u're trying build the bootloader, please make sure you're using esp-idf fork from odroid-go repository.

**Comment by 1371030** [comment]
thanks!
