### ISSUE TITLE
Screen orientation is wrong

### ISSUE THREAD

**Issue by SunnyIMG** [pebri86/esplay-base-firmware#9]
The screen is mirrored, and the orientation is wrong, so I want to ask where can I change the screen orientation and mirroring?

**Comment by pebri86** [comment]
hi, may i ask you some question.
did you use your own hardware/board?
did you installed from your own compiled or from released?

**Comment by SunnyIMG** [comment]
@pebri86 It's like this, I saw someone else's modified hardware on https://oshwhub.com/zxp1107/esplay_copy_copy_copy, and someone has made it successfully. At present, there is only a problem with my screen. It may be that I bought the wrong one.  , may need to modify the screen initialization code?  But I don't know where to modify it.

**Comment by SunnyIMG** [comment]
I flashed the bootloader in the release, lcd is still the same wrong

**Comment by pebri86** [comment]
can you confirm the lcd controller type?

**Comment by pebri86** [comment]
![Screenshot_2022-03-31-16-33-23-847_com.github.android.jpg](https://user-images.githubusercontent.com/3339304/161024819-92122fbf-492c-48de-964e-1a42515fa1b0.jpg)

if you use master branch
try change line 344 to false in swap x y

**Comment by SunnyIMG** [comment]
> 你能确认液晶控制器的类型吗？

yes. ili9341v

**Comment by SunnySnowYu** [comment]
> 你能确认液晶控制器的类型吗？

![Uploading Screenshot_2022-03-31-17-40-53-36_090d9ae461b065ca11c329abb9cd0d70.jpg…]()

**Comment by SunnyIMG** [comment]
![Screenshot_2022-03-31-17-40-53-36_090d9ae461b065ca11c329abb9cd0d70](https://user-images.githubusercontent.com/49270612/161026565-4c7869de-9445-4ebd-ba7a-7996e526a249.jpg)

**Comment by pebri86** [comment]
![Screenshot_2022-03-31-16-33-23-847_com.github.android.jpg](https://user-images.githubusercontent.com/3339304/161024819-92122fbf-492c-48de-964e-1a42515fa1b0.jpg)

if you use master branch
try change line 344 to false in swap x y

also you can add this code

` 
 ​esp_lcd_panel_mirror​(​panel_handle, ​true, ​false);
`
try every combination true and false value until it displayed correctly

**Comment by SunnyIMG** [comment]
And the screen display is mirrored, will it also be solved this way?

**Comment by SunnyIMG** [comment]
> ![截图_2022-03-31-16-33-23-847_com.github.android.jpg](https://user-images.githubusercontent.com/3339304/161024819-92122fbf-492c-48de-964e-1a42515fa1b0.jpg)
> 
> 如果您使用主分支 尝试在交换 xy 中将第 344 行更改为 false
> 
> 您也可以添加此代码
> 
> ` ​esp_lcd_panel_mirror​(​panel_handle, ​true, ​false);` 尝试每个组合真假值，直到它正确显示

I just need to open main.c, then compile esplay-base-firmware.bin, is it ok to flash in?
